---
- name: create VMs
  hosts: localhost
  gather_facts: no

  vars:
    default_user: vyos
    default_pass: vyos
    new_vyos_pass: superpass
  vars_files:
      - vars/guests_iso.yml

  tasks:
      - name: Get list of VMs
        virt:
            command: "list_vms"
        register: virt_vms

      - name: Create vm
        command: virt-install -n {{ item.name }}
                 --ram {{ item.mem }}
                 --vcpus {{ item.cpu }}
                 --cdrom {{ item.url }}
                 --os-type {{ item.os.type }}
                 --os-variant {{ item.os.variant }}
                 --network network=default
                 --graphics vnc
                 --{{item.virt_hypervisor}}
                 --virt-type {{ item.virt_type }}
                 --disk path={{item.disk.path}}/{{item.name}}.qcow2,bus=virtio,size={{item.disk.size}}
                 --noautoconsole
        when: item.name not in virt_vms.list_vms
        with_items: "{{ guests }}"

      - name: get guest info
        virt: command=info
        register: virt_info

      - name: make sure all vms are running
        virt:
            name: "{{ item.name }}"
            state: running
        with_items: "{{ guests }}"

      - name: Waiting for VMs to load
        pause: seconds=20

      - name: Install VyOS
        expect:
          echo: yes
          command: virsh console {{ item.name }} --force
          responses:
            'Connected to domain': ''
            'vyos login': "{{default_user}}"
            'assword': "{{default_pass}}"
            'vyos@vyos': "install image"
            'Would you like to continue?': ""
            'Partition \(Auto\/Parted\/Skip\)': ''
            'Install the image on\?': ''
            'Continue\?': "Yes"
            'How big of a root partition': ''
            'What would you like to name': ''
            'Which one should I copy to': ''
            'Enter password for user': "{{ new_vyos_pass}}"
            'Retype password for user': "{{ new_vyos_pass}}"
            'Which drive should GRUB modify the boot partition on?': ''
            'Setting up grub': 'reboot now'
        with_items: "{{ guests }}"

      - name: make sure all vms are running
        virt:
            name: "{{ item.name }}"
            state: running
        with_items: "{{ guests }}"

      - name: Wait for VMs is loaded
        pause: seconds=15

      - name: Post Install Commands
        command:
          scripts/connect_console_post_install_iso.sh
          {{ item.name }}
          {{default_user}}
          {{new_vyos_pass}}
          {{ item.address }}
        with_items: "{{ guests }}"

