---
- name: create VMs
  hosts: localhost
  gather_facts: no

  vars:
    default_user: vyos
    default_pass: vyos
    new_vyos_pass: superpass
    qcow_template: /home/sever/Downloads/ISO/vyos-1.2.5-amd64.qcow2
  vars_files:
      - vars/guests_qcow.yml

  tasks:
      - name: Get list of VMs
        virt:
            command: "list_vms"
        register: virt_vms

      - name: Copy qcow2 from template "{{ qcow_template }}"
        become: true
        copy:
            src: "{{ qcow_template }}"
            dest: "{{ item.disk.path }}/{{ item.name }}.qcow2"
        when: item.name not in virt_vms.list_vms
        with_items: "{{ guests }}"


      - name: Create vm
        command: virt-install -n {{ item.name }}
                 --ram {{ item.mem }}
                 --vcpus {{ item.cpu }}
                 --os-type {{ item.os.type }}
                 --os-variant {{ item.os.variant }}
                 --network network=default
                 --graphics vnc
                 --{{item.virt_hypervisor}}
                 --virt-type {{ item.virt_type }}
                 --disk path={{item.disk.path}}/{{item.name}}.qcow2,bus=virtio
                 --import
                 --noautoconsole
        when: item.name not in virt_vms.list_vms
        with_items: "{{ guests }}"

      - name: make sure all vms are running
        virt:
            name: "{{ item.name }}"
            state: running
        with_items: "{{ guests }}"

      - name: Waiting for VMs to load
        pause: seconds=5

      - name: Post Install Commands
        command:
          scripts/connect_console_post_install_qcow.sh
          {{ item.name }}
          {{ default_user }}
          {{ default_pass }}
          {{ new_vyos_pass }}
          {{ item.address }}
          {{ item.name}}
        with_items: "{{ guests }}"
