---

- hosts: r11

  connection: network_cli
  gather_facts: 'no'

  tasks:
    - name: Configure remote r11
      vyos_config:
        lines:
          - set system host-name r11-ansible
          - set system name-server 1.1.1.1
          - set service ssh disable-host-validation
          - set system login user docker authentication public-keys docker@work type ssh-rsa
          - set system login user docker authentication public-keys docker@work key "{{ lookup('file', 'id_rsa_docker.pub') }}"
        #backup: yes
